version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node:10.16.0
        working_directory: ~/repo/comake
        steps:
            - checkout
            # Download and cache dependencies
            # - restore_cache:
                  # keys:
                      # - v1-dependencies-{{ checksum "package.json" }}
                      # - v1-dependencies-
            - run:
                  name: Install Dependencies
                  command: npm install
                  name: install firebase
                  command: npm install -g -D firebase-tools
            - save_cache:
                  key: v1-npm-deps-{{ checksum "package-lock.json" }}
                  paths:
                      - ./node_modules
            - run:
                  name: Build
                  command: npm build
            - run:
                  name: Firebase Deploy
                  command: firebase deploy --token "1//01RzCohHJqbQ-CgYIARAAGAESNwF-L9IrB0mI-OY25BL540tp2IO5Jok4mwVTIxl2HZE-6QmIKwtD_0zEHi5r4Ykdpu40wCI0Tac" --only hosting
