version: 2.1
orbs:
  node: circleci/node@1.1.6
  working_directory: ~/repo
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: 
                  name: Install dependencies
                  command: npm install
            - run: npm test
            - run: 
                  name: Firebase Deploy
                  command: ./node_modules/.bin/firebase deploy token "$FIREBASE_TOKEN" --only hosting
